# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b5b81c62c00cab8f270aba20f3ddefa"
name = "europa"
handle = "europa"
application_url = "https://ethnic-kidney-purchase-tomorrow.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "eigen-europa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ethnic-kidney-purchase-tomorrow.trycloudflare.com/auth/callback",
  "https://ethnic-kidney-purchase-tomorrow.trycloudflare.com/auth/shopify/callback",
  "https://ethnic-kidney-purchase-tomorrow.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
